#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YBP_final_zola
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="YBP2")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLoading(Loading instance);
    partial void UpdateLoading(Loading instance);
    partial void DeleteLoading(Loading instance);
    partial void InsertLOGIN(LOGIN instance);
    partial void UpdateLOGIN(LOGIN instance);
    partial void DeleteLOGIN(LOGIN instance);
    partial void InsertOrder1(Order1 instance);
    partial void UpdateOrder1(Order1 instance);
    partial void DeleteOrder1(Order1 instance);
    partial void InsertTT(TT instance);
    partial void UpdateTT(TT instance);
    partial void DeleteTT(TT instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::YBP_final_zola.Properties.Settings.Default.YBP2ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Loading> Loadings
		{
			get
			{
				return this.GetTable<Loading>();
			}
		}
		
		public System.Data.Linq.Table<LOGIN> LOGINs
		{
			get
			{
				return this.GetTable<LOGIN>();
			}
		}
		
		public System.Data.Linq.Table<Order1> Order1s
		{
			get
			{
				return this.GetTable<Order1>();
			}
		}
		
		public System.Data.Linq.Table<TT> TTs
		{
			get
			{
				return this.GetTable<TT>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Loading")]
	public partial class Loading : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _Date;
		
		private string _Order_number;
		
		private string _Invoice_number;
		
		private string _Destination_name;
		
		private string _Product;
		
		private string _volume;
		
		private string _truck_number;
		
		private string _FDCnumber;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnOrder_numberChanging(string value);
    partial void OnOrder_numberChanged();
    partial void OnInvoice_numberChanging(string value);
    partial void OnInvoice_numberChanged();
    partial void OnDestination_nameChanging(string value);
    partial void OnDestination_nameChanged();
    partial void OnProductChanging(string value);
    partial void OnProductChanged();
    partial void OnvolumeChanging(string value);
    partial void OnvolumeChanged();
    partial void Ontruck_numberChanging(string value);
    partial void Ontruck_numberChanged();
    partial void OnFDCnumberChanging(string value);
    partial void OnFDCnumberChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public Loading()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Order_number", DbType="VarChar(50)")]
		public string Order_number
		{
			get
			{
				return this._Order_number;
			}
			set
			{
				if ((this._Order_number != value))
				{
					this.OnOrder_numberChanging(value);
					this.SendPropertyChanging();
					this._Order_number = value;
					this.SendPropertyChanged("Order_number");
					this.OnOrder_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Invoice_number", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Invoice_number
		{
			get
			{
				return this._Invoice_number;
			}
			set
			{
				if ((this._Invoice_number != value))
				{
					this.OnInvoice_numberChanging(value);
					this.SendPropertyChanging();
					this._Invoice_number = value;
					this.SendPropertyChanged("Invoice_number");
					this.OnInvoice_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Destination_name", DbType="VarChar(50)")]
		public string Destination_name
		{
			get
			{
				return this._Destination_name;
			}
			set
			{
				if ((this._Destination_name != value))
				{
					this.OnDestination_nameChanging(value);
					this.SendPropertyChanging();
					this._Destination_name = value;
					this.SendPropertyChanged("Destination_name");
					this.OnDestination_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product", DbType="VarChar(50)")]
		public string Product
		{
			get
			{
				return this._Product;
			}
			set
			{
				if ((this._Product != value))
				{
					this.OnProductChanging(value);
					this.SendPropertyChanging();
					this._Product = value;
					this.SendPropertyChanged("Product");
					this.OnProductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_volume", DbType="VarChar(50)")]
		public string volume
		{
			get
			{
				return this._volume;
			}
			set
			{
				if ((this._volume != value))
				{
					this.OnvolumeChanging(value);
					this.SendPropertyChanging();
					this._volume = value;
					this.SendPropertyChanged("volume");
					this.OnvolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_truck_number", DbType="VarChar(50)")]
		public string truck_number
		{
			get
			{
				return this._truck_number;
			}
			set
			{
				if ((this._truck_number != value))
				{
					this.Ontruck_numberChanging(value);
					this.SendPropertyChanging();
					this._truck_number = value;
					this.SendPropertyChanged("truck_number");
					this.Ontruck_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDCnumber", DbType="VarChar(50)")]
		public string FDCnumber
		{
			get
			{
				return this._FDCnumber;
			}
			set
			{
				if ((this._FDCnumber != value))
				{
					this.OnFDCnumberChanging(value);
					this.SendPropertyChanging();
					this._FDCnumber = value;
					this.SendPropertyChanged("FDCnumber");
					this.OnFDCnumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOGIN")]
	public partial class LOGIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _username;
		
		private string _Password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public LOGIN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Order1")]
	public partial class Order1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<System.DateTime> _Acct;
		
		private string _Dealer_name;
		
		private string _Product;
		
		private string _QTY;
		
		private string _Number;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAcctChanging(System.Nullable<System.DateTime> value);
    partial void OnAcctChanged();
    partial void OnDealer_nameChanging(string value);
    partial void OnDealer_nameChanged();
    partial void OnProductChanging(string value);
    partial void OnProductChanged();
    partial void OnQTYChanging(string value);
    partial void OnQTYChanged();
    partial void OnNumberChanging(string value);
    partial void OnNumberChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public Order1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Acct", DbType="Date")]
		public System.Nullable<System.DateTime> Acct
		{
			get
			{
				return this._Acct;
			}
			set
			{
				if ((this._Acct != value))
				{
					this.OnAcctChanging(value);
					this.SendPropertyChanging();
					this._Acct = value;
					this.SendPropertyChanged("Acct");
					this.OnAcctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dealer_name", DbType="VarChar(50)")]
		public string Dealer_name
		{
			get
			{
				return this._Dealer_name;
			}
			set
			{
				if ((this._Dealer_name != value))
				{
					this.OnDealer_nameChanging(value);
					this.SendPropertyChanging();
					this._Dealer_name = value;
					this.SendPropertyChanged("Dealer_name");
					this.OnDealer_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product", DbType="VarChar(50)")]
		public string Product
		{
			get
			{
				return this._Product;
			}
			set
			{
				if ((this._Product != value))
				{
					this.OnProductChanging(value);
					this.SendPropertyChanging();
					this._Product = value;
					this.SendPropertyChanged("Product");
					this.OnProductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY", DbType="VarChar(50)")]
		public string QTY
		{
			get
			{
				return this._QTY;
			}
			set
			{
				if ((this._QTY != value))
				{
					this.OnQTYChanging(value);
					this.SendPropertyChanging();
					this._QTY = value;
					this.SendPropertyChanged("QTY");
					this.OnQTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this.OnNumberChanging(value);
					this.SendPropertyChanging();
					this._Number = value;
					this.SendPropertyChanged("Number");
					this.OnNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TT")]
	public partial class TT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Seq;
		
		private string _plateN;
		
		private string _Orders;
		
		private string _Destination;
		
		private string _Product;
		
		private System.Nullable<System.DateTime> _Arrival_date;
		
		private System.Nullable<System.DateTime> _Assign_date;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSeqChanging(string value);
    partial void OnSeqChanged();
    partial void OnplateNChanging(string value);
    partial void OnplateNChanged();
    partial void OnOrdersChanging(string value);
    partial void OnOrdersChanged();
    partial void OnDestinationChanging(string value);
    partial void OnDestinationChanged();
    partial void OnProductChanging(string value);
    partial void OnProductChanged();
    partial void OnArrival_dateChanging(System.Nullable<System.DateTime> value);
    partial void OnArrival_dateChanged();
    partial void OnAssign_dateChanging(System.Nullable<System.DateTime> value);
    partial void OnAssign_dateChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public TT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seq", DbType="VarChar(50)")]
		public string Seq
		{
			get
			{
				return this._Seq;
			}
			set
			{
				if ((this._Seq != value))
				{
					this.OnSeqChanging(value);
					this.SendPropertyChanging();
					this._Seq = value;
					this.SendPropertyChanged("Seq");
					this.OnSeqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plateN", DbType="VarChar(50)")]
		public string plateN
		{
			get
			{
				return this._plateN;
			}
			set
			{
				if ((this._plateN != value))
				{
					this.OnplateNChanging(value);
					this.SendPropertyChanging();
					this._plateN = value;
					this.SendPropertyChanged("plateN");
					this.OnplateNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orders", DbType="VarChar(50)")]
		public string Orders
		{
			get
			{
				return this._Orders;
			}
			set
			{
				if ((this._Orders != value))
				{
					this.OnOrdersChanging(value);
					this.SendPropertyChanging();
					this._Orders = value;
					this.SendPropertyChanged("Orders");
					this.OnOrdersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Destination", DbType="VarChar(50)")]
		public string Destination
		{
			get
			{
				return this._Destination;
			}
			set
			{
				if ((this._Destination != value))
				{
					this.OnDestinationChanging(value);
					this.SendPropertyChanging();
					this._Destination = value;
					this.SendPropertyChanged("Destination");
					this.OnDestinationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product", DbType="VarChar(50)")]
		public string Product
		{
			get
			{
				return this._Product;
			}
			set
			{
				if ((this._Product != value))
				{
					this.OnProductChanging(value);
					this.SendPropertyChanging();
					this._Product = value;
					this.SendPropertyChanged("Product");
					this.OnProductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Arrival_date", DbType="Date")]
		public System.Nullable<System.DateTime> Arrival_date
		{
			get
			{
				return this._Arrival_date;
			}
			set
			{
				if ((this._Arrival_date != value))
				{
					this.OnArrival_dateChanging(value);
					this.SendPropertyChanging();
					this._Arrival_date = value;
					this.SendPropertyChanged("Arrival_date");
					this.OnArrival_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Assign_date", DbType="Date")]
		public System.Nullable<System.DateTime> Assign_date
		{
			get
			{
				return this._Assign_date;
			}
			set
			{
				if ((this._Assign_date != value))
				{
					this.OnAssign_dateChanging(value);
					this.SendPropertyChanging();
					this._Assign_date = value;
					this.SendPropertyChanged("Assign_date");
					this.OnAssign_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
